---
- name: Create d4g-stalwart directory
  file:
    path: "/opt/d4g-stalwart"
    state: directory

- name: Creating d4g-stalwart template
  template:
    src: "{{ item }}.j2"
    dest: /opt/d4g-stalwart/{{ item }}
  with_items:
    - docker-compose.yml
    - stalwart.env

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-stalwart
  tags:
    - pull
  when: inventory_hostname == deploy_on

- name: Up
  command: docker stack deploy -c docker-compose.yml d4g-stalwart
  args:
    chdir: /opt/d4g-stalwart
  tags:
    - up
  when: is_swarm_leader | default(false)

- import_role:
    name: roles/utilities/s3-backup
  vars:
    service_name: stalwart
    data_dir: /opt/d4g-stalwart/data
  tags:
    - backup
    - service
  when: inventory_hostname == deploy_on

- import_role:
    name: roles/utilities/sql-backup
  vars:
    service: d4g-stalwart
    service_dir: /opt/d4g-stalwart
    pgsql_host: "{{ lookup('env', 'POLETECH_DB_HOST') }}"
    pgsql_port: "{{ lookup('env', 'POLETECH_DB_PORT') }}"
    pgsql_user: stalwart
    pgsql_password: "{{ lookup('env', 'NC_DB_PASSWORD') }}"
    pgsql_database: stalwart
  tags:
    - backup
    - service
  when: inventory_hostname == deploy_on
